### ISSUE TITLE
SSL CN validace

### ISSUE THREAD

**Issue by ErikZigo** [keboola/db-extractor-mysql#7]
Od  PHP 5.6 je v php defaultne zapla validace common name u SSL.

Nektere certifikaty cloudovych sluzeb proto nemusi fungovat, protoze nemaji CN shodne s hostname:
https://bugs.php.net/bug.php?id=71845

Toto nastaveni se neda pro soucasnou verzi PDO vypnout.

Pro klienty, kteri nemaji moznost vygenerovat spravny SSL certifikat je k dispozici MySQL ex postaveny nad PHP5.5.9
https://github.com/keboola/db-extractor-mysql-php55

**Comment by ujovlado** [comment]
V PHP 7 by to uz malo ist vypnut v pohode, myslim, ze sa jedna o:

```php
[
    \PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
]
```

**Comment by ujovlado** [comment]
@pivnicek I think of proper fix of this:

1. implement option to turn off that verification
2. get rid of that custom db-ex on php 5.5 :hankey: (it was temporary fix)

But I'm still not 100% sure about 1., because what if users just turn off that validation rather than fixing the issue with CN? ... But, we can say, we gave them option to do it properly.

Anyway, it can help users which are not allowed to fix CN problem (3rd party provider, as @ErikZigo said) and we can drop another piece of deprecated stuff.
